blank_issues_enabled: false
contact_links:
  - name: General Readarr documentation
    url: https://wiki.servarr.com/readarr
    about: Setup guides and FAQ for Readarr in general (not fork-specific).
