// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'activeTab': string;
  'dropZone': string;
  'dropZonePrompt': string;
  'dropZoneSubtext': string;
  'errorAlert': string;
  'helpText': string;
  'previewContainer': string;
  'previewFilename': string;
  'previewImage': string;
  'tabButton': string;
  'tabButtons': string;
  'textInput': string;
  'uploadIcon': string;
}
export const cssExports: CssExports;
export default cssExports;
